jobs:
  include:
  - stage: web-test
    language: node_js
    node_js:
    - '15'
    cache:
      yarn: true
    before_script: npm i -g yarn
    script: |
      make install
      make test
stages:
- web-test
