jobs:
  include:
  - stage: web-test
    language: node_js
    node_js:
    - '12'
    cache:
      yarn: true
    before_script: 'npm i -g yarn'
    script: |
      yarn lint
      yarn test
      yarn build
  - stage: web-deploy
    language: node_js
    node_js:
    - '12'
    before_script: 'npm i -g yarn'
    script: 'yarn build'
    deploy:
      provider: heroku
      app: feast-web
      api_key:
        secure: "evtP+dEEdAcUNOnkrfEhu04H4G8g+LxCAc0nRKDILW10Z2K6dNqGwkdnuTls6OEpHZlO34zXS/K2Up+jyLfanIThak41PXxlyKUjEnAbJp3A25gZLMqHH3URCWZFDv1EioP1qSHI4/KrCg2BUMjUxALvx87wgFInTGAxzT/Nk2EKXC/JvczXP83fSDKFMephVQyN+k1DfY4b41dm1wiBb+kHpniA7q7NHGHSOzCmmTgvBABHWpMKcelsevk3XvqPCTvbrADZMYQm8JWsr268o8z0guof+P7h84R11V+HfkV6DBWicXEAPHVcW2H0WfzCw9ceu9Q6zrcbRnFq85dk0BmfAJXX6aX7kfJmhX9x6UEIe5FCgK3ib7UjDJp0nMSS3scwfSTgxNoftlfztm1eJRLQXlLqzpZxgZem5hlIsCxf/bq2WDwkkaxVX27Egk9MFkdFKTA2g8L+H+431v2yGqqgMBvFM3rB+1pLzkDWxa2iJRgxC/S6qNUjzDJnbVI+cxudXuJwfDIok/53yLmHSjWheOth5SnBZTd4CepW/j54BT94dzKjLZJ6u1x+ndebszN85bGcecWfRfY9mFtMHiEONaxAOMEVbBNt8xyjpJMe+08W7ajteRKMqIIbFSQkhFmivGQzycHLl4V5yFSE3iIcQu7bsMGVZOYZo3khzD8="
  - stage: api-test
    language: java
    jdk:
    - openjdk8
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    script: "./gradlew test"
  - stage: api-deploy
    language: java
    jdk:
      - openjdk8
    script: |
      ./gradlew assemble -x test
    deploy:
      provider: heroku
      app: feast-api-dev
      api_key:
        secure: "evtP+dEEdAcUNOnkrfEhu04H4G8g+LxCAc0nRKDILW10Z2K6dNqGwkdnuTls6OEpHZlO34zXS/K2Up+jyLfanIThak41PXxlyKUjEnAbJp3A25gZLMqHH3URCWZFDv1EioP1qSHI4/KrCg2BUMjUxALvx87wgFInTGAxzT/Nk2EKXC/JvczXP83fSDKFMephVQyN+k1DfY4b41dm1wiBb+kHpniA7q7NHGHSOzCmmTgvBABHWpMKcelsevk3XvqPCTvbrADZMYQm8JWsr268o8z0guof+P7h84R11V+HfkV6DBWicXEAPHVcW2H0WfzCw9ceu9Q6zrcbRnFq85dk0BmfAJXX6aX7kfJmhX9x6UEIe5FCgK3ib7UjDJp0nMSS3scwfSTgxNoftlfztm1eJRLQXlLqzpZxgZem5hlIsCxf/bq2WDwkkaxVX27Egk9MFkdFKTA2g8L+H+431v2yGqqgMBvFM3rB+1pLzkDWxa2iJRgxC/S6qNUjzDJnbVI+cxudXuJwfDIok/53yLmHSjWheOth5SnBZTd4CepW/j54BT94dzKjLZJ6u1x+ndebszN85bGcecWfRfY9mFtMHiEONaxAOMEVbBNt8xyjpJMe+08W7ajteRKMqIIbFSQkhFmivGQzycHLl4V5yFSE3iIcQu7bsMGVZOYZo3khzD8="
stages:
- web-test
- name: web-deploy
  if: branch = master
- api-test