micronaut:
  application:
    name: io.feast.api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:1234
            - https://feast-web.herokuapp.com